# Product Configuration
export PRODUCT_NAME="SecuEdge" # Replace with your product name
export FREEBSD_REPO_BASE=https://github.com/sagarsec/FreeBSD-src.git # FreeBSD source repo
export POUDRIERE_PORTS_GIT_URL=https://github.com/sagarsec/FreeBSD-ports.git # FreeBSD ports repo

# Branch Configuration
export FREEBSD_BRANCH=RELENG_2_7_2 # Branch of FreeBSD sources to build
export POUDRIERE_PORTS_GIT_BRANCH=RELENG_2_7_2 # Branch of FreeBSD ports to build

# Disable Staging Builds
unset USE_PKG_REPO_STAGING # Disable staging build

# Architecture
export DEFAULT_ARCH_LIST="amd64.amd64" # Build x64 ISO only

# Signing Key
export PKG_REPO_SIGNING_COMMAND="/root/sign/sign.sh ${PKG_REPO_SIGN_KEY}"

# Server Configuration
export myIPAddress=$(ifconfig -a | grep inet | grep '.' | head -1 | cut -d ' ' -f 2)
export PKG_REPO_SERVER_DEVEL="http://${myIPAddress}/packages"
export PKG_REPO_SERVER_RELEASE="http://${myIPAddress}/packages"
export PKG_REPO_SERVER_STAGING="http://${myIPAddress}/packages" # Needed even if staging is disabled

# Source Configuration
export SRCCONF="/root/pfsense/tmp/FreeBSD-src/release/conf/${PRODUCT_NAME}_build_src.conf"
